### ISSUE TITLE
Some observed CVTest bugs

### ISSUE THREAD

**Issue by antagomir** [reptalex/WrightFisher#1]
library(devtools)
load_all("WrightFisher")
set.seed(2)

wfp <- WFP(nSpecies=15, lambda=25)
R <- wfp[[2]] # Timesteps x Species matrix

cvt2 = CVTest(ntests = 1000, R, regress = "t")

Error in CVTest(ntests = 1000, R, regress = "t") : 
  unknown inputt "regress" - must be either "f" or "time"

cvt2 = CVTest(ntests = 1000, R, regress = "time")
Error: object 'm' not found

**Comment by reptalex** [comment]
Hey Leo!

Thanks for picking this up - I've updated the code to squash this bug.

I've also allowed an input "tm" for the timepoints of your samples to
correct the variance of the jumps in case the time steps between samples
are not all the same.

Best,
Alex

**Comment by antagomir** [comment]
Ok thanks. Not yet sure how to use it with CVTest as I still get the following error:

> cvt = CVTest(ntests = 1000, R, regress = "tm")
> Error in CVTest(ntests = 1000, R, regress = "tm") : 
>   unknown inputt "regress" - must be either "f" or "time"
> cvt = CVTest(ntests = 1000, R, regress = "time")
> Error: object 'm' not found

So a usage example would be useful for a newbie such as me.

**Comment by reptalex** [comment]
Bug fixed!
